export const hiragana = 

`あ,A,Hiragana letter A
い,I,Hiragana letter I
う,U,Hiragana letter U
え,E,Hiragana letter E
お,O,Hiragana letter O
か,KA,Hiragana letter KA
が,GA,Hiragana letter GA
き,KI,Hiragana letter KI
ぎ,GI,Hiragana letter GI
く,KU,Hiragana letter KU
ぐ,GU,Hiragana letter GU
け,KE,Hiragana letter KE
げ,GE,Hiragana letter GE
こ,KO,Hiragana letter KO
ご,GO,Hiragana letter GO
さ,SA,Hiragana letter SA
ざ,ZA,Hiragana letter ZA
し,SHI,Hiragana letter SHI
じ,ZI,Hiragana letter ZI
す,SU,Hiragana letter SU
ず,ZU,Hiragana letter ZU
せ,SE,Hiragana letter SE
ぜ,ZE,Hiragana letter ZE
そ,SO,Hiragana letter SO
ぞ,ZO,Hiragana letter ZO
た,TA,Hiragana letter TA
だ,DA,Hiragana letter DA
ち,CHI,Hiragana letter CHI
ぢ,JI,Hiragana letter JI
つ,TSU,Hiragana letter TSU
づ,ZU,Hiragana letter ZU
て,TE,Hiragana letter TE
で,DE,Hiragana letter DE
と,TO,Hiragana letter TO
ど,DO,Hiragana letter DO
な,NA,Hiragana letter NA
に,NI,Hiragana letter NI
ぬ,NU,Hiragana letter NU
ね,NE,Hiragana letter NE
の,NO,Hiragana letter NO
は,HA,Hiragana letter HA
ば,BA,Hiragana letter BA
ぱ,PA,Hiragana letter PA
ひ,HI,Hiragana letter HI
び,BI,Hiragana letter BI
ぴ,PI,Hiragana letter PI
ふ,FU,Hiragana letter FU
ぶ,BU,Hiragana letter BU
ぷ,PU,Hiragana letter PU
へ,HE,Hiragana letter HE
べ,BE,Hiragana letter BE
ぺ,PE,Hiragana letter PE
ほ,HO,Hiragana letter HO
ぼ,BO,Hiragana letter BO
ぽ,PO,Hiragana letter PO
ま,MA,Hiragana letter MA
み,MI,Hiragana letter MI
む,MU,Hiragana letter MU
め,ME,Hiragana letter ME
も,MO,Hiragana letter MO
や,YA,Hiragana letter YA
ゆ,YU,Hiragana letter YU
よ,YO,Hiragana letter YO
ら,RA,Hiragana letter RA
り,RI,Hiragana letter RI
る,RU,Hiragana letter RU
れ,RE,Hiragana letter RE
ろ,RO,Hiragana letter RO
わ,WA,Hiragana letter WA
を,O,Hiragana letter O
ん,N,Hiragana letter N`;