export const katakana = 

`ア,A,Katakana letter A
イ,I,Katakana letter I
ウ,U,Katakana letter U
エ,E,Katakana letter E
オ,O,Katakana letter O
カ,KA,Katakana letter KA
ガ,GA,Katakana letter GA
キ,KI,Katakana letter KI
ギ,GI,Katakana letter GI
ク,KU,Katakana letter KU
グ,GU,Katakana letter GU
ケ,KE,Katakana letter KE
ゲ,GE,Katakana letter GE
コ,KO,Katakana letter KO
ゴ,GO,Katakana letter GO
サ,SA,Katakana letter SA
ザ,ZA,Katakana letter ZA
シ,SI,Katakana letter SI
ジ,ZI,Katakana letter ZI
ス,SU,Katakana letter SU
ズ,ZU,Katakana letter ZU
セ,SE,Katakana letter SE
ゼ,ZE,Katakana letter ZE
ソ,SO,Katakana letter SO
ゾ,ZO,Katakana letter ZO
タ,TA,Katakana letter TA
ダ,DA,Katakana letter DA
チ,CHI,Katakana letter CHI
ヂ,JI,Katakana letter JI
ツ,TSU,Katakana letter TSU
ヅ,ZU,Katakana letter ZU
テ,TE,Katakana letter TE
デ,DE,Katakana letter DE
ト,TO,Katakana letter TO
ド,DO,Katakana letter DO
ナ,NA,Katakana letter NA
ニ,NI,Katakana letter NI
ヌ,NU,Katakana letter NU
ネ,NE,Katakana letter NE
ノ,NO,Katakana letter NO
ハ,HA,Katakana letter HA
バ,BA,Katakana letter BA
パ,PA,Katakana letter PA
ヒ,HI,Katakana letter HI
ビ,BI,Katakana letter BI
ピ,PI,Katakana letter PI
フ,HU,Katakana letter FU
ブ,BU,Katakana letter BU
プ,PU,Katakana letter PU
ヘ,HE,Katakana letter HE
ベ,BE,Katakana letter BE
ペ,PE,Katakana letter PE
ホ,HO,Katakana letter HO
ボ,BO,Katakana letter BO
ポ,PO,Katakana letter PO
マ,MA,Katakana letter MA
ミ,MI,Katakana letter MI
ム,MU,Katakana letter MU
メ,ME,Katakana letter ME
モ,MO,Katakana letter MO
ヤ,YA,Katakana letter YA
ユ,YU,Katakana letter YU
ヨ,YO,Katakana letter YO
ラ,RA,Katakana letter RA
リ,RI,Katakana letter RI
ル,RU,Katakana letter RU
レ,RE,Katakana letter RE
ロ,RO,Katakana letter RO
ワ,WA,Katakana letter WA
ヲ,WO,Katakana letter O
ン,N,Katakana letter N`

let next = 

`ヰ,WI,Katakana letter WI
ヱ,WE,Katakana letter WE
ヴ,VU,Katakana letter VU`
